FROM golang:1.22-alpine

WORKDIR /app

RUN go install github.com/a-h/templ/cmd/templ@latest
RUN go install github.com/cosmtrek/air@latest

COPY go.mod go.sum ./
RUN go mod download

ENV NODE_VERSION 20.12.2

RUN apk add --update nodejs npm

COPY package*.json ./

RUN npx update-browserslist-db@latest
RUN npm install

CMD ["air", "-c", ".air.toml"]
